### ISSUE TITLE
belongsToMany ?

### ISSUE THREAD

**Issue by waptik** [vickenstein/mongoose-association#3]
Hi and thanks for this plugin. Is there a way for a schema to directly have a `belongsToMany` method?

**Comment by vickenstein** [comment]
belongsToMany is the same as ```belongsTo``` - really depends the inverse relation you want to setup.
Since this is mongo not sql, there is actually a ```hasMany('AModel', {nested: true})``` to created a ```belongsToMany``` without creating a through collection. I would love to learn more of your specific use case and improve on the library.

**Comment by waptik** [comment]
> 
> 
> belongsToMany is the same as `belongsTo` - really depends the inverse relation you want to setup.
> Since this is mongo not sql, there is actually a `hasMany('AModel', {nested: true})` to created a `belongsToMany` without creating a through collection. I would love to learn more of your specific use case and improve on the library.

Thanks for your reply. What i'm looking to achieve is as follow:
say i have two models: `Computer` and `Student` for a computer lab management system and we know that one/more computer can be used by one/more students at different times.
So instead of saying `StudentSchema.hasMany('Computer')` 👎 , i'd like to reference the student-computer relationship from within the ComputerSchema which will be `ComputerSchema.belongsToMany('Student')` 👍

**Comment by vickenstein** [comment]
Cool, you are describing a ManyToMany Relationship.
This can be accomplished in two ways using mongoose association.
1. using a through table - you can create a third schema e.g. // this is the more normalized approach
```javascript
const StudentComputerSchema  = new Mongoose.schema({})
StudentComputerSchema.belongsTo('Student')
StudentComputerSchema.belongsTo('Computer')
///////
const StudentSchema = new Mongoose.schema({})
StudentSchema.hasMany('StudentComputer')
StudentSchema.hasMany('Computer', { through: 'StudentComputer' }) // <- this is the same as sequelize belongsToMany but using Mongo!
///////
const ComputerSchema = new Mongoose.schema({})
ComputerSchema.hasMany('StudentComputer')
ComputerSchema.hasMany('Student', { through: 'StudentComputer' })
////////
```
2. using nested hasMany association: // this is the less normalized approach
```javascript
const StudentSchema = new Mongoose.schema({})

const ComputerSchema = new Mongoose.schema({})
ComputerSchema.hasMany('Student', { nested: true })
```

**Comment by waptik** [comment]
Which one of these would you use if it was you?

**Comment by vickenstein** [comment]
Sorry took me a while to get back to ya, but I would use the former because is a more normalize relationship and easier to maintain. the only advantage of the latter is the ability to also able to store the order of the hasMany relationship.

**Comment by waptik** [comment]
No biggies, all good. Guess i'll go for the normalized option.
Thanks for your feedback.
